name: test
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - numpy >=1.23
  - nomkl

    # Testing
  - autoflake
  - black
  - codecov
  - isort
  - mypy
  - pytest
  - pytest-cov
