name: test
channels:
  - conda-forge
  - pytorch
dependencies:
    # Base depends
  - python
  - numpy
  - nomkl

    # Backends
  - tensorflow-base ==1.2
  - dask ==1.1
  - sparse ==0.7
  - pytorch-cpu ==1.0.1

    # Testing
  - pytest
  - codecov
  - pytest-cov
