name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
        enable-cache: true

    - name: Install
      run: uv pip install -e ".[docs]"

    - name: Build Docs
      run: uv run mkdocs build

    # Only deploy if main, otherwise just build for testing
    - name: Deploy
      if: endsWith(github.ref, '/main')
      run: uv run mkdocs gh-deploy --force
