name: Linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  mypy:
    name: MyPy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
        enable-cache: true

    - name: MyPy
      run: uv run --with ".[lint]" mypy opt_einsum

  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
        enable-cache: true

    - name: Lint
      run: make format-check
